---
- hosts: test 
  gather_facts: no
  become: yes
  become_method: sudo

  tasks:
    #- name: check the services
    #  yum:
     #   name: "{{ item }}"
      #  state: absent

      # with_items:
       # - httpd
       # - telnet 
#        - apr
       # - nmap
       # - zip
      - name: ensure a list of packages installed
        yum:
          name: "{{ packages }}"
        vars:
          packages:
          - httpd
          - httpd-tools  
